name: login
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pocketbase: ^0.22.0
  shared_preferences: ^2.5.2
  path: ^ 1.9.1
  get: ^4.7.2
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.5
  path_provider: ^2.1.5
  file_picker: ^9.1.0
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  mime: ^2.0.0
  open_filex: ^4.7.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  video_player: ^2.9.3
  chewie: ^1.11.0
  mobile_scanner: ^6.0.7
  permission_handler: ^11.4.0
  http: ^1.3.0
  csv: ^6.0.0
  fl_chart: ^0.70.2
  flutter_dotenv: ^5.2.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android: true
  ios: true
  web: false
  fullscreen: true 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/solar/sensor.csv