name: login
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pocketbase: ^0.22.0
  shared_preferences: ^2.5.2
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  path: ^ 1.9.1
  get: ^4.7.2
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.5
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.5
  file_picker: ^9.1.0
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  mime: ^2.0.0
  open_filex: ^4.7.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  video_player: ^2.9.3
  video_player_media_kit: ^1.0.5
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  chewie: ^1.11.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android: true
  ios: true
  web: false
  fullscreen: true 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true